name: Publish multiarch container on ghcr.io
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Build and push Spilo multiarch container
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Derive postgresql version
      id: pgVersion
      working-directory: postgres-appliance
      run: |
        pgVersion=$(sed -n 's/^ARG PGVERSION=\([1-9][0-9]*\).*$/\1/p' Dockerfile)
        echo "::set-output name=version::$pgVersion"

    - name: Generate docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/zalando/spilo-${{ steps.pgVersion.outputs.version }}
        tags: |
          type=ref,event=tag

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: network=host

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: "postgres-appliance/"
        file: "postgres-appliance/Dockerfile"
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        
    - name: Test spilo docker image 
      run: bash postgres-appliance/tests/test_spilo.sh 

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}